### ISSUE TITLE
Regresion with Persona 5 Royal (on SteamDeck)

### ISSUE THREAD

**Issue by ahjolinna** [Etaash-mathamsetty/Proton#29]
# Compatibility Report
- Name of the game with compatibility issues: Persona 5 Royal
- Steam AppID of the game: 1687950

## System Information
- SteamDeck/SteamOS 3.7.14 (build 20250701.1) 
- Video driver version: Mesa 24.3.4 (git-8d0948917e)
- Kernel version: Linux 6.11.11-valve20-1-neptune-611-gd35c3ed359a0
- Proton version: EM-10.0-28 / EM-10.0-27

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 [steam-1687950.log](https://github.com/user-attachments/files/21565140/steam-1687950.log)

## Symptoms 
When loading save file game freezes after few seconds , works fine with v25
I tested also on my Desktop with Nvidia gpu, and there was no issue

**Comment by Etaash-mathamsetty** [comment]
Your log didn't upload properly I guess but this  issue has probably already been fixed for the next version (whenever it comes out)

**Comment by ahjolinna** [comment]
well just in case here is the reupload [steam-1687950.log](https://github.com/user-attachments/files/21567349/steam-1687950.log)

**Comment by Etaash-mathamsetty** [comment]
should be fixed with 10.0-29 (please reopen if not)

**Comment by ahjolinna** [comment]
no still the same, even worse as it gets stuck on loading screen when I loaded some save file.

I also tried loading new game and it freezes when dialog ends.

it was mentioned in the changelogs that Borderless Windowed are recommend to use, and I have been using that as the graphics are worse on fullscreen (horrible AA, this has always been an issue)

here is the log when starting new/fresh game and it freezes after the dialog ends: 
[steam-1687950.log](https://github.com/user-attachments/files/21589722/steam-1687950.log)

PS. apparently I don't have permission to reopen this issue

**Comment by Etaash-mathamsetty** [comment]
btw using winewayland with gamescope is unsupported and may cause other issues with the python script (Luckily it falls back to x11)

**Comment by Etaash-mathamsetty** [comment]
This looks pretty much undebuggable (without owning the game); if above doesn't work, I'd probably need log with PROTON_LOG=+relay (if that even works with proton)

**Comment by ahjolinna** [comment]
hmm, yeah the PROTON_LOG=+relay does work but created a 8gb log file, BUT now there is another bug, after the into video there is transition phase to menu which now loops so I'm stuck/freezes there :D 

I can send the 8gb log if you want that

**Comment by ahjolinna** [comment]
well the log is here to download: https://www.swisstransfer.com/d/3af8fc37-8091-44e4-975b-51d1c16fe90d

I was thinking about testing the game on SteamDeck/SteamOS desktop mode (KDE) but then I remember it's still stuck on using x11

**Comment by Etaash-mathamsetty** [comment]
> well the log is here to download: https://www.swisstransfer.com/d/3af8fc37-8091-44e4-975b-51d1c16fe90d
> 
> I was thinking about testing the game on SteamDeck/SteamOS desktop mode (KDE) but then I remember it's still stuck on using x11

Could you compress the file first?
Also what happens when you disable steam input?

**Comment by ahjolinna** [comment]
here is ~500mb compressed file of the log: https://www.swisstransfer.com/d/36f89522-baf7-4b97-90d0-8ec869df796e

well I tried to run the game on SteamDeck desktop mode now with steam input disable and it didnt freeze anymore but I couldn't do much for obvious reasons (I could try to plugin a keyboard).....oh anyway, small side note for some reason this time it did open the game in really small window (~1/4th) and when screen res is only 1280×800

**Comment by Etaash-mathamsetty** [comment]
What happens if you try proton experimental bleeding edge beta ? I don't see anything in proton-em that could cause issues with steam input

**Comment by Etaash-mathamsetty** [comment]
fixed for proton-EM 10.0-2D
