### ISSUE TITLE
[Wine-Wayland] Arc Raiders - Some special characters cannot be bound (but do work fine in chat)

### ISSUE THREAD

**Issue by noel-personal** [Etaash-mathamsetty/Proton#69]
# Compatibility Report
- Name of the game with compatibility issues: ARC Raiders
- Steam AppID of the game: 1808500

## System Information
- GPU: 7900XTX
- Video driver version: Mesa 25.2.7
- Kernel version: 6.17.8
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/noel-personal/806dd838d99e389f9cfd5bdc35a8d39c
- Proton version: proton-EM-10.0-32

## I confirm:
- [ ✅ ] that I haven't found an existing compatibility report for this game.
- [ ✅ ] that I have checked whether there are updates for my system available.

### Using wine-wayland with custom keybinds some keys cannot be mapped to an action.

Probably an edge case for me but I am left handed and use the "German (Switzerland, no dead keys) / ch_de_nodeadkeys" keyboard layout. 
When I attempt to rebind the actions ingame the game does not react, showing me "NONE" for all keys/characters that do not work. Clicking okay shows the keybind as "UNASSIGNED". Those actions do not work in-game.

<img width="1963" height="818" alt="Image" src="https://github.com/user-attachments/assets/45a5cce3-1bec-4016-8647-09edd8f2cf3b" />

<img width="1543" height="858" alt="Image" src="https://github.com/user-attachments/assets/9512a718-74da-4d00-baad-caf8f3233585" />

For me the following characters do not work. I attach a corresponding picture with the keys pressed for clarity).
`öäü$¨^-`

<img width="1858" height="624" alt="Image" src="https://github.com/user-attachments/assets/dc9a2c41-399f-4c04-ab9f-0db30e4cc9f6" />

All those characters do work when using the in-game chat.

<img width="1169" height="1014" alt="Image" src="https://github.com/user-attachments/assets/707e80e2-6294-4a10-b5db-04df7a70fe32" />

That issue only happens when using PROTON_ENABLE_WAYLAND=1. Everything works fine when using xwayland.

## Reproduction

* In the main menu (speranza) go to settings and then controls
* Attempt to rebind an action with the aforementioned characters/keys
* Play a game -> Enter the practice range (making sure the bind does indeed not work)
* Return to main menu
* Open the chat with T
* Attempt using those characters in the chat

[steam-1808500.tar.gz](https://github.com/user-attachments/files/23610012/steam-1808500.tar.gz)

**Comment by Etaash-mathamsetty** [comment]
Could you send a log with `PROTON_LOG=+key,+keyboard` looking at https://kbdlayout.info/kbdsg/virtualkeys shows that we are implementing everything correctly in winewayland

**Comment by Etaash-mathamsetty** [comment]
Fixed for 10.0-33

**Comment by noel-personal** [comment]
Oh wow that was quick. Amazing work! I assume the logs are not needed anymore? 😅

**Comment by kecicz** [comment]
Hi, thanks for looking into this issue.
The last proton EM update unfortunately did not solve everything for me. 
I use czech QWERTZ keyboard layout. This layout does not have numbers on the top of the keyboard, but czech special characters, so I often have to rebind these keys.
The tested game for me is Satisfactory. Before this issue was resolved, none of these keys worked. In the latest version, some of the keys work correctly, but some are interpreted as different characters, or still as "None". 

Screenshots from the game's settings:

<img width="1464" height="570" alt="Image" src="https://github.com/user-attachments/assets/e7c79839-43b1-411c-8d6e-612d15b2e141" />
<img width="1464" height="570" alt="Image" src="https://github.com/user-attachments/assets/180876f7-ce10-4581-8856-43b2fadd4880" />

The correct characters should be: "+ěščřžýáíé"

<img width="850" height="450" alt="Image" src="https://github.com/user-attachments/assets/b599ab8a-a300-438c-9fe8-fc78fc8330b3" />

Here is the recorded log with "+key,+keyboard" as requested:
 

[steam-526870.log.tar.gz](https://github.com/user-attachments/files/24652837/steam-526870.log.tar.gz)

**Comment by Etaash-mathamsetty** [comment]
> Hi, thanks for looking into this issue.
> The last proton EM update unfortunately did not solve everything for me. 
> I use czech QWERTZ keyboard layout. This layout does not have numbers on the top of the keyboard, but czech special characters, so I often have to rebind these keys.
> The tested game for me is Satisfactory. Before this issue was resolved, none of these keys worked. In the latest version, some of the keys work correctly, but some are interpreted as different characters, or still as "None". 
> 
> Screenshots from the game's settings:
> 
> <img width="1464" height="570" alt="Image" src="https://github.com/user-attachments/assets/e7c79839-43b1-411c-8d6e-612d15b2e141" />
> <img width="1464" height="570" alt="Image" src="https://github.com/user-attachments/assets/180876f7-ce10-4581-8856-43b2fadd4880" />
> 
> The correct characters should be: "+ěščřžýáíé"
> 
> <img width="850" height="450" alt="Image" src="https://github.com/user-attachments/assets/b599ab8a-a300-438c-9fe8-fc78fc8330b3" />
> 
> Here is the recorded log with "+key,+keyboard" as requested:
>  
> 
> [steam-526870.log.tar.gz](https://github.com/user-attachments/files/24652837/steam-526870.log.tar.gz)

This looks to be a completely different issue (that upstream would also share) if u could open a new one that would be helpful to make me not forget about it

**Comment by Etaash-mathamsetty** [comment]
Actually, don't bother; I already fixed it
