### ISSUE TITLE
[Wine-Wayland] Old School Runescape

### ISSUE THREAD

**Issue by ahjolinna** [Etaash-mathamsetty/Proton#78]
# Compatibility Report
- Name of the game with compatibility issues: Old School RuneScape
- Steam AppID of the game: 1343370

## System Information
- GPU: RTX 3060TI
- Video driver version: 580.105.08
- Kernel version: 6.17.9-arch1-1
- Link to full system information report as Gist: [link](https://gist.githubusercontent.com/ahjolinna/b6e047698c08fca8c9735f11b4d4b20e/raw/b50e318caa08755ee55dec903872cd4f99b9b0da/gistfile1.txt)
- Steam Runtime System Info: [file](https://gist.githubusercontent.com/ahjolinna/61bf56e3da6a740f439eef199b870087/raw/2a9f57b0aea9c660d521f8be76fe5bbf0f485e5b/gistfile1.txt)
- Proton version: GE-Proton10-26 & Proton-EM 10.0-32

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Game wont launch just stays running in the background and cant close game normally and if I try to close steam the client crashes 

log file using GE-Proton10-26 : [steam-1343370.log](https://github.com/user-attachments/files/24200481/steam-1343370.log)

**Comment by ahjolinna** [comment]
if it matters, when I try to close steam-client when the game is still running in the background and it crashed I get this error: 

<img width="572" height="325" alt="Image" src="https://github.com/user-attachments/assets/d7ab737f-e16a-47ee-9f86-db4988435d8e" />

```
           PID: 1606709 (steam)
           UID: 1000 (ahjolinna)
           GID: 1000 (ahjolinna)
        Signal: 11 (SEGV)
     Timestamp: Wed 2025-12-17 00:15:45 EET (14s ago)
  Command Line: /home/ahjolinna/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam -srt-logger-opened -no-cef-sandbox
    Executable: /home/ahjolinna/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.valvesoftware.Steam-596002790.scope
          Unit: user@1000.service
     User Unit: app-flatpak-com.valvesoftware.Steam-596002790.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ahjolinna)
       Boot ID: 4aac7fe303f543e0b3679b35d0b04359
    Machine ID: af01112386594d3d8ac3f935574e641e
      Hostname: KDE-Linux
       Storage: /var/lib/systemd/coredump/core.steam.1000.4aac7fe303f543e0b3679b35d0b04359.1606709.1765923345000000.zst (present)
  Size on Disk: 29.7M
       Message: Process 1606709 (steam) of user 1000 dumped core.
                
                Stack trace of thread 8440:
                #0  0x00000000e501d184 n/a (n/a + 0x0)
                #1  0x00000000f3bb2d2e _ZN16SteamThreadTools7CThread22ThreadExceptionWrapperEPv (libtier0_s.so + 0x32d2e)
                #2  0x00000000f3bb05fe n/a (libtier0_s.so + 0x305fe)
                #3  0x00000000f3bb0ec0 CatchAndWriteMiniDumpExForVoidPtrFn (libtier0_s.so + 0x30ec0)
                #4  0x00000000f3bb0f08 CatchAndWriteMiniDumpForVoidPtrFn (libtier0_s.so + 0x30f08)
                #5  0x00000000f3bb59a2 _ZN16SteamThreadTools7CThread10ThreadProcEPv (libtier0_s.so + 0x359a2)
                #6  0x00000000f7a45c8a n/a (/app/lib/i386-linux-gnu/libc.so.6 + 0x98c8a)
                ELF object binary architecture: Intel 80386


```

**Comment by Etaash-mathamsetty** [comment]
Fixed for 10.0-34

**Comment by ahjolinna** [comment]
Same as RS3, didn't fix for me ...now it just tries to launch it but nothing happens ..not even the crash thing

[steam-1343370.log](https://github.com/user-attachments/files/25806987/steam-1343370.log)

**Comment by Etaash-mathamsetty** [comment]
Unfortunately I cannot reproduce it, maybe something wrong with your egl driver?

Yeah both of them work, likely nvidia driver memes
